//! The loaded kernel modules: which kernel runs, whether it is still the
//! installed package's, and the modules no package installed.

use std::collections::HashMap;
use std::fs;

use super::{Found, files, packaged};
use crate::autorun::Category;
use crate::paths::file_name;
use crate::rules::RuleId;
use crate::sweep::collect::Scope;

/// The running kernel's release, as its modules directory is named.
pub(super) fn kernel_release(scope: &Scope<'_>) -> Option<String> {
    release_named(&fs::read_to_string(scope.root.join(OSRELEASE)).ok()?)
}

/// Where the running kernel says which release it is, under the root.
const OSRELEASE: &str = "proc/sys/kernel/osrelease";

/// The release the text of `osrelease` names.
fn release_named(text: &str) -> Option<String> {
    // It names a directory: nothing that leads elsewhere.
    let release = text.trim();
    (!release.is_empty() && !release.contains('/') && release != "." && release != "..")
        .then(|| release.to_string())
}

/// Whether the running kernel is still the installed package's. After a
/// kernel update the running kernel's modules are gone, or put back by a
/// helper (kernel-modules-hook) outside any package, until the next boot:
/// then nothing there can be checked against a package. `modules.dep` is
/// generated by depmod; `pkgbase` comes with the kernel package.
pub(super) fn kernel_installed(scope: &Scope<'_>, modules_root: &str) -> bool {
    let installed = format!("{modules_root}/pkgbase");
    scope.root.join(&installed).is_file() && packaged(scope, &installed)
}

/// Loaded modules no package installed, and the taint flag.
pub(super) fn kernel(scope: &Scope<'_>, found: &mut Found) {
    let missed = "loaded kernel modules were not checked";
    let read = fs::read_to_string(scope.root.join(OSRELEASE));
    let Some(text) = found.read(scope, &format!("/{OSRELEASE}"), missed, read) else {
        return;
    };
    let Some(release) = release_named(&text) else {
        found.not_checked(
            scope,
            format!("/{OSRELEASE}: names no kernel release; {missed}"),
        );
        return;
    };
    let modules_root = format!("usr/lib/modules/{release}");
    if kernel_installed(scope, &modules_root) {
        loaded_modules(scope, &modules_root, found);
    } else {
        found.notes.push(format!(
            "kernel modules not checked: kernel {release} is no longer installed as a package (updated); they are checked again after a reboot"
        ));
    }
    let taint = super::kernel::taint(scope);
    if taint != 0 {
        found
            .notes
            .push(format!("the kernel is tainted ({})", taint_flags(taint)));
    }
}

/// Repository packages that ship modules built outside the kernel's own
/// tree, by the start of their name: the kernel marks those out-of-tree,
/// and the proprietary ones unsigned.
const OUT_OF_TREE_PACKAGES: &[&str] = &[
    "nvidia",
    "virtualbox",
    "vmware",
    "zfs",
    "spl",
    "v4l2loopback",
    "broadcom-wl",
    "r8168",
    "r8125",
    "acpi_call",
    "bbswitch",
    "tp_smapi",
    "vhba",
    "evdi",
    "xone",
    "xpadneo",
    "openrazer",
    "ddcci",
    "lkrg",
    "digimend",
    "rtl88",
    "rtw8",
    "facetimehd",
    "zenpower",
    "ryzen_smu",
    "nct6687d",
    "vendor-reset",
    "kvmfr",
    "sysdig",
    "falco",
];

fn loaded_modules(scope: &Scope<'_>, modules_root: &str, found: &mut Found) {
    let files: HashMap<String, String> =
        fs::read_to_string(scope.root.join(modules_root).join("modules.dep"))
            .unwrap_or_default()
            .lines()
            .filter_map(|line| line.split(':').next())
            .map(|path| (module_name(path), path.to_string()))
            .collect();
    let dkms = scope.root.join("var/lib/dkms").is_dir();
    let read = fs::read_to_string(scope.root.join("proc/modules"));
    let loaded = found
        .read(
            scope,
            "/proc/modules",
            "loaded kernel modules were not checked",
            read,
        )
        .unwrap_or_default();
    for name in loaded
        .lines()
        .filter_map(|line| line.split_whitespace().next())
    {
        let Some(file) = files.get(name) else {
            found.add_missing(
                scope,
                Category::KernelModule,
                &format!("sys/module/{name}"),
                "not among the installed modules",
                format!("module {name} is loaded but is not among this kernel's installed modules"),
                RuleId::UnknownKernelModule,
            );
            continue;
        };
        let path = format!("{modules_root}/{file}");
        if packaged(scope, &path) {
            packaged_module(scope, name, file, &path, found);
        } else if dkms && path.contains("/updates/dkms/") {
            found.add(
                scope,
                Category::KernelModule,
                &path,
                format!("module {name}, built by DKMS"),
                None,
            );
        } else {
            found.add(
                scope,
                Category::KernelModule,
                &path,
                format!("module {name} is loaded"),
                Some(RuleId::UnknownKernelModule),
            );
        }
    }
}

/// A loaded module whose file at `path` a package installed: the file is
/// compared with what the package recorded, and what the kernel says of
/// the module it loaded with what that package ships.
fn packaged_module(scope: &Scope<'_>, name: &str, file: &str, path: &str, found: &mut Found) {
    if !files::intact(scope, found, Category::KernelModule, path) {
        found.add(
            scope,
            Category::KernelModule,
            path,
            format!("module {name} is loaded, and its file is not what its package installed"),
            Some(RuleId::UnknownKernelModule),
        );
    }
    // `O` is out-of-tree, `E` unsigned: neither is said of a module the
    // kernel's own package built.
    let taint = fs::read_to_string(scope.root.join("sys/module").join(name).join("taint"))
        .unwrap_or_default();
    if !taint.contains(['O', 'E']) {
        return;
    }
    if file.starts_with("kernel/") {
        // Not the file it was loaded under that name from.
        found.add(
            scope,
            Category::KernelModule,
            path,
            format!(
                "module {name} is loaded out-of-tree or unsigned under an in-tree module's name"
            ),
            Some(RuleId::UnknownKernelModule),
        );
        return;
    }
    let package = scope
        .index
        .owner(path)
        .map(|owned| scope.index.package(owned))
        .unwrap_or_default();
    if !OUT_OF_TREE_PACKAGES
        .iter()
        .any(|known| package.starts_with(known))
    {
        found.add(
            scope,
            Category::KernelModule,
            path,
            format!(
                "module {name} is out-of-tree or unsigned, and its package ({package}) is not one known to ship such modules"
            ),
            Some(RuleId::UnknownKernelModule),
        );
    }
}

/// A module's name from its `modules.dep` path: `kernel/x/snd-hda.ko.zst`
/// is `snd_hda`.
pub(super) fn module_name(path: &str) -> String {
    let file = file_name(path);
    file.split(".ko").next().unwrap_or(file).replace('-', "_")
}

fn taint_flags(taint: u64) -> String {
    let known = [
        (0, "a proprietary module"),
        (12, "an out-of-tree module"),
        (13, "an unsigned module"),
        (15, "a kernel live patch"),
    ];
    let mut reasons: Vec<&str> = known
        .iter()
        .filter(|(bit, _)| taint & (1 << bit) != 0)
        .map(|(_, reason)| *reason)
        .collect();
    if reasons.is_empty() {
        reasons.push("see /proc/sys/kernel/tainted");
    }
    format!("flags {taint}: {}", reasons.join(", "))
}
